#!/bin/bash
# sh -c "npm install"
# sh -c "ls -a"
# sh -c "echo $PWD"
# sh -c "echidna-test --version"
# sh -c "ln"
# sh -c "crytic-compile --version"
# sh -c "npm install"
# sh -c "echidna-test . --contract Fallback"
bash -c "ln -s /root/.local /github/.local"
bash -c "ls -a ../"
bash -c "ls -a"
bash -c "echo $PWD"
bash -c "echidna-test --version"
bash -c "crytic-compile --version"