name: Echidna audits without action
on: push

jobs:
  echidna-audit-Fallback:
    name: Echidna audit Fallback contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install NPM packages
        run: npm install
      - name: Install Slither
        run: pip install slither-analyzer
      - name: Download Echidna
        run: https://github.com/crytic/echidna/releases/download/v1.7.2/echidna-test-1.7.2-Ubuntu-18.04.tar.gz && tar -xf echidna-test-1.7.2-Ubuntu-18.04.tar.gz
      - name: Creating init file
        run: python ./.github/actions/action-a/create_init.py
      - name: Run Echidna
        run: ./echidna-test . --contract Test --config Fallback.config.yml