name: Echidna audits workflow
on: push

jobs:
  echidna-audit-Fallback:
    name: Echidna audit Fallback contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/action-a
        with:
          CONTRACT_NAME: "Fallback"
          working-directory: /root/repo